// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/comunidad/cien-requiem/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/comunidad/cien-requiem">> = Specific
  const handler = {} as typeof import("../../../src/app/comunidad/cien-requiem/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/comunidad/novenas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/comunidad/novenas">> = Specific
  const handler = {} as typeof import("../../../src/app/comunidad/novenas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/comunidad/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/comunidad">> = Specific
  const handler = {} as typeof import("../../../src/app/comunidad/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/jornada/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/jornada">> = Specific
  const handler = {} as typeof import("../../../src/app/jornada/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/perfil/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/perfil">> = Specific
  const handler = {} as typeof import("../../../src/app/perfil/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/rosario/en-vivo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/rosario/en-vivo">> = Specific
  const handler = {} as typeof import("../../../src/app/rosario/en-vivo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/rosario/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/rosario">> = Specific
  const handler = {} as typeof import("../../../src/app/rosario/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/link-email/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/link-email">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/link-email/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/session">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/community/intentions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/community/intentions">> = Specific
  const handler = {} as typeof import("../../../src/app/api/community/intentions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/cron/sweep/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/sweep">> = Specific
  const handler = {} as typeof import("../../../src/app/api/cron/sweep/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/daily-content/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/daily-content">> = Specific
  const handler = {} as typeof import("../../../src/app/api/daily-content/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/garden/state/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/garden/state">> = Specific
  const handler = {} as typeof import("../../../src/app/api/garden/state/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../../src/app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/llama/current/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/llama/current">> = Specific
  const handler = {} as typeof import("../../../src/app/api/llama/current/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/llama/join/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/llama/join">> = Specific
  const handler = {} as typeof import("../../../src/app/api/llama/join/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/llama/light/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/llama/light">> = Specific
  const handler = {} as typeof import("../../../src/app/api/llama/light/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/novenas/join/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/novenas/join">> = Specific
  const handler = {} as typeof import("../../../src/app/api/novenas/join/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/novenas/mine/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/novenas/mine">> = Specific
  const handler = {} as typeof import("../../../src/app/api/novenas/mine/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/novenas/progress/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/novenas/progress">> = Specific
  const handler = {} as typeof import("../../../src/app/api/novenas/progress/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/novenas/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/novenas">> = Specific
  const handler = {} as typeof import("../../../src/app/api/novenas/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/queues/consume/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/queues/consume">> = Specific
  const handler = {} as typeof import("../../../src/app/api/queues/consume/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/rosario/heartbeat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rosario/heartbeat">> = Specific
  const handler = {} as typeof import("../../../src/app/api/rosario/heartbeat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/rosario/snapshot/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rosario/snapshot">> = Specific
  const handler = {} as typeof import("../../../src/app/api/rosario/snapshot/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/rosario/transition/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rosario/transition">> = Specific
  const handler = {} as typeof import("../../../src/app/api/rosario/transition/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/tasks/community-counts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tasks/community-counts">> = Specific
  const handler = {} as typeof import("../../../src/app/api/tasks/community-counts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/tasks/complete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tasks/complete">> = Specific
  const handler = {} as typeof import("../../../src/app/api/tasks/complete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/tasks/progress/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tasks/progress">> = Specific
  const handler = {} as typeof import("../../../src/app/api/tasks/progress/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/tasks/today/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tasks/today">> = Specific
  const handler = {} as typeof import("../../../src/app/api/tasks/today/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
